<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251109004052 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id SERIAL NOT NULL, country_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, city VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4FBF094FF92F3E70 ON company (country_id)');
        $this->addSql('COMMENT ON COLUMN company.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE country (id SERIAL NOT NULL, visa_availability_id INT DEFAULT NULL, expected_country_id INT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5373C966D641A739 ON country (visa_availability_id)');
        $this->addSql('CREATE INDEX IDX_5373C9661F702855 ON country (expected_country_id)');
        $this->addSql('COMMENT ON COLUMN country.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE country_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, country_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_78659372E559DFD1 ON country_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_78659372F92F3E70 ON country_i18n (country_id)');
        $this->addSql('COMMENT ON COLUMN country_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE curriculum (id SERIAL NOT NULL, location_id INT DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, is_freelance BOOLEAN NOT NULL, freelance_company_name VARCHAR(255) DEFAULT NULL, is_available BOOLEAN NOT NULL, has_visa BOOLEAN NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BE2A7C364D218E ON curriculum (location_id)');
        $this->addSql('COMMENT ON COLUMN curriculum.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE curriculum_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, curriculum_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BAD77FC9E559DFD1 ON curriculum_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_BAD77FC95AEA4428 ON curriculum_i18n (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN curriculum_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE education (id SERIAL NOT NULL, school_id INT DEFAULT NULL, curriculum_id INT DEFAULT NULL, starting_date DATE NOT NULL, ending_date DATE DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DB0A5ED2C32A47EE ON education (school_id)');
        $this->addSql('CREATE INDEX IDX_DB0A5ED25AEA4428 ON education (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN education.starting_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN education.ending_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN education.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE education_skill (education_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(education_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_E2B1FED02CA1BD71 ON education_skill (education_id)');
        $this->addSql('CREATE INDEX IDX_E2B1FED05585C142 ON education_skill (skill_id)');
        $this->addSql('CREATE TABLE education_technology (education_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY(education_id, technology_id))');
        $this->addSql('CREATE INDEX IDX_A99FA5602CA1BD71 ON education_technology (education_id)');
        $this->addSql('CREATE INDEX IDX_A99FA5604235D463 ON education_technology (technology_id)');
        $this->addSql('CREATE TABLE education_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, education_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, diploma VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15CFA527E559DFD1 ON education_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_15CFA5272CA1BD71 ON education_i18n (education_id)');
        $this->addSql('COMMENT ON COLUMN education_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE experience (id SERIAL NOT NULL, company_id INT DEFAULT NULL, curriculum_id INT DEFAULT NULL, starting_date DATE NOT NULL, ending_date DATE DEFAULT NULL, is_current_work BOOLEAN NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_590C103979B1AD6 ON experience (company_id)');
        $this->addSql('CREATE INDEX IDX_590C1035AEA4428 ON experience (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN experience.starting_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN experience.ending_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN experience.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE experience_skill (experience_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(experience_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_3D6F986146E90E27 ON experience_skill (experience_id)');
        $this->addSql('CREATE INDEX IDX_3D6F98615585C142 ON experience_skill (skill_id)');
        $this->addSql('CREATE TABLE experience_technology (experience_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY(experience_id, technology_id))');
        $this->addSql('CREATE INDEX IDX_1BC2EDF146E90E27 ON experience_technology (experience_id)');
        $this->addSql('CREATE INDEX IDX_1BC2EDF14235D463 ON experience_technology (technology_id)');
        $this->addSql('CREATE TABLE experience_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, experience_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB46D78BE559DFD1 ON experience_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_AB46D78B46E90E27 ON experience_i18n (experience_id)');
        $this->addSql('COMMENT ON COLUMN experience_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE language (id SERIAL NOT NULL, curriculum_id INT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D4DB71B55AEA4428 ON language (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN language.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE language_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, language_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, level VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CD5FF2DAE559DFD1 ON language_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_CD5FF2DA82F1BAF4 ON language_i18n (language_id)');
        $this->addSql('COMMENT ON COLUMN language_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE link (id SERIAL NOT NULL, project_id INT DEFAULT NULL, curriculum_id INT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, is_project BOOLEAN NOT NULL, url VARCHAR(255) DEFAULT NULL, repository_url VARCHAR(255) DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_36AC99F1166D1F9C ON link (project_id)');
        $this->addSql('CREATE INDEX IDX_36AC99F15AEA4428 ON link (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN link.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE link_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, link_id INT DEFAULT NULL, project_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E118A3FE559DFD1 ON link_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_4E118A3FADA40271 ON link_i18n (link_id)');
        $this->addSql('CREATE INDEX IDX_4E118A3F166D1F9C ON link_i18n (project_id)');
        $this->addSql('COMMENT ON COLUMN link_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE locale (id SERIAL NOT NULL, label VARCHAR(255) NOT NULL, shortened VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN locale.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE picture (id SERIAL NOT NULL, project_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, path TEXT NOT NULL, mime_type VARCHAR(255) NOT NULL, bytes_size INT NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, sha256 VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_16DB4F89166D1F9C ON picture (project_id)');
        $this->addSql('COMMENT ON COLUMN picture.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE project (id SERIAL NOT NULL, status_id INT DEFAULT NULL, company_id INT DEFAULT NULL, school_id INT DEFAULT NULL, curriculum_id INT DEFAULT NULL, creation_date DATE DEFAULT NULL, is_hidden BOOLEAN NOT NULL, short_description TEXT NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE6BF700BD ON project (status_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE979B1AD6 ON project (company_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEC32A47EE ON project (school_id)');
        $this->addSql('CREATE INDEX IDX_2FB3D0EE5AEA4428 ON project (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN project.creation_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN project.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE project_technology (project_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY(project_id, technology_id))');
        $this->addSql('CREATE INDEX IDX_ECC5297F166D1F9C ON project_technology (project_id)');
        $this->addSql('CREATE INDEX IDX_ECC5297F4235D463 ON project_technology (technology_id)');
        $this->addSql('CREATE TABLE project_tag (project_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(project_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_91F26D60166D1F9C ON project_tag (project_id)');
        $this->addSql('CREATE INDEX IDX_91F26D60BAD26311 ON project_tag (tag_id)');
        $this->addSql('CREATE TABLE project_skill (project_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(project_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_4D68EDE9166D1F9C ON project_skill (project_id)');
        $this->addSql('CREATE INDEX IDX_4D68EDE95585C142 ON project_skill (skill_id)');
        $this->addSql('CREATE TABLE project_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, project_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, cv_description TEXT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C6C7D08EE559DFD1 ON project_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_C6C7D08E166D1F9C ON project_i18n (project_id)');
        $this->addSql('COMMENT ON COLUMN project_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE school (id SERIAL NOT NULL, country_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, city VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F99EDABBF92F3E70 ON school (country_id)');
        $this->addSql('COMMENT ON COLUMN school.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE skill (id SERIAL NOT NULL, curriculum_id INT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3DE4775AEA4428 ON skill (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN skill.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE skill_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, skill_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B8178424E559DFD1 ON skill_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_B81784245585C142 ON skill_i18n (skill_id)');
        $this->addSql('COMMENT ON COLUMN skill_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE status (id SERIAL NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN status.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE status_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, status_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C750B502E559DFD1 ON status_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_C750B5026BF700BD ON status_i18n (status_id)');
        $this->addSql('COMMENT ON COLUMN status_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tag (id SERIAL NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN tag.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tag_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, tag_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1159A720E559DFD1 ON tag_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_1159A720BAD26311 ON tag_i18n (tag_id)');
        $this->addSql('COMMENT ON COLUMN tag_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE technology (id SERIAL NOT NULL, curriculum_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, icon VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F463524D5AEA4428 ON technology (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN technology.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "user" (id SERIAL NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE work_type (id SERIAL NOT NULL, curriculum_id INT DEFAULT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_751DE6115AEA4428 ON work_type (curriculum_id)');
        $this->addSql('COMMENT ON COLUMN work_type.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE work_type_i18n (id SERIAL NOT NULL, locale_id INT NOT NULL, work_type_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, datetime_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A5175CBE559DFD1 ON work_type_i18n (locale_id)');
        $this->addSql('CREATE INDEX IDX_4A5175CB108734B1 ON work_type_i18n (work_type_id)');
        $this->addSql('COMMENT ON COLUMN work_type_i18n.datetime_immutable IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966D641A739 FOREIGN KEY (visa_availability_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C9661F702855 FOREIGN KEY (expected_country_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE country_i18n ADD CONSTRAINT FK_78659372E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE country_i18n ADD CONSTRAINT FK_78659372F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE curriculum ADD CONSTRAINT FK_7BE2A7C364D218E FOREIGN KEY (location_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE curriculum_i18n ADD CONSTRAINT FK_BAD77FC9E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE curriculum_i18n ADD CONSTRAINT FK_BAD77FC95AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education ADD CONSTRAINT FK_DB0A5ED2C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education ADD CONSTRAINT FK_DB0A5ED25AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_skill ADD CONSTRAINT FK_E2B1FED02CA1BD71 FOREIGN KEY (education_id) REFERENCES education (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_skill ADD CONSTRAINT FK_E2B1FED05585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_technology ADD CONSTRAINT FK_A99FA5602CA1BD71 FOREIGN KEY (education_id) REFERENCES education (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_technology ADD CONSTRAINT FK_A99FA5604235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_i18n ADD CONSTRAINT FK_15CFA527E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE education_i18n ADD CONSTRAINT FK_15CFA5272CA1BD71 FOREIGN KEY (education_id) REFERENCES education (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C103979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C1035AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_skill ADD CONSTRAINT FK_3D6F986146E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_skill ADD CONSTRAINT FK_3D6F98615585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_technology ADD CONSTRAINT FK_1BC2EDF146E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_technology ADD CONSTRAINT FK_1BC2EDF14235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_i18n ADD CONSTRAINT FK_AB46D78BE559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience_i18n ADD CONSTRAINT FK_AB46D78B46E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE language ADD CONSTRAINT FK_D4DB71B55AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE language_i18n ADD CONSTRAINT FK_CD5FF2DAE559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE language_i18n ADD CONSTRAINT FK_CD5FF2DA82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F1166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F15AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE link_i18n ADD CONSTRAINT FK_4E118A3FE559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE link_i18n ADD CONSTRAINT FK_4E118A3FADA40271 FOREIGN KEY (link_id) REFERENCES link (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE link_i18n ADD CONSTRAINT FK_4E118A3F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE picture ADD CONSTRAINT FK_16DB4F89166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE6BF700BD FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEC32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE5AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_technology ADD CONSTRAINT FK_ECC5297F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_technology ADD CONSTRAINT FK_ECC5297F4235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE9166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_skill ADD CONSTRAINT FK_4D68EDE95585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_i18n ADD CONSTRAINT FK_C6C7D08EE559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_i18n ADD CONSTRAINT FK_C6C7D08E166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE4775AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_i18n ADD CONSTRAINT FK_B8178424E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_i18n ADD CONSTRAINT FK_B81784245585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_i18n ADD CONSTRAINT FK_C750B502E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE status_i18n ADD CONSTRAINT FK_C750B5026BF700BD FOREIGN KEY (status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tag_i18n ADD CONSTRAINT FK_1159A720E559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tag_i18n ADD CONSTRAINT FK_1159A720BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE technology ADD CONSTRAINT FK_F463524D5AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE work_type ADD CONSTRAINT FK_751DE6115AEA4428 FOREIGN KEY (curriculum_id) REFERENCES curriculum (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE work_type_i18n ADD CONSTRAINT FK_4A5175CBE559DFD1 FOREIGN KEY (locale_id) REFERENCES locale (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE work_type_i18n ADD CONSTRAINT FK_4A5175CB108734B1 FOREIGN KEY (work_type_id) REFERENCES work_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094FF92F3E70');
        $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C966D641A739');
        $this->addSql('ALTER TABLE country DROP CONSTRAINT FK_5373C9661F702855');
        $this->addSql('ALTER TABLE country_i18n DROP CONSTRAINT FK_78659372E559DFD1');
        $this->addSql('ALTER TABLE country_i18n DROP CONSTRAINT FK_78659372F92F3E70');
        $this->addSql('ALTER TABLE curriculum DROP CONSTRAINT FK_7BE2A7C364D218E');
        $this->addSql('ALTER TABLE curriculum_i18n DROP CONSTRAINT FK_BAD77FC9E559DFD1');
        $this->addSql('ALTER TABLE curriculum_i18n DROP CONSTRAINT FK_BAD77FC95AEA4428');
        $this->addSql('ALTER TABLE education DROP CONSTRAINT FK_DB0A5ED2C32A47EE');
        $this->addSql('ALTER TABLE education DROP CONSTRAINT FK_DB0A5ED25AEA4428');
        $this->addSql('ALTER TABLE education_skill DROP CONSTRAINT FK_E2B1FED02CA1BD71');
        $this->addSql('ALTER TABLE education_skill DROP CONSTRAINT FK_E2B1FED05585C142');
        $this->addSql('ALTER TABLE education_technology DROP CONSTRAINT FK_A99FA5602CA1BD71');
        $this->addSql('ALTER TABLE education_technology DROP CONSTRAINT FK_A99FA5604235D463');
        $this->addSql('ALTER TABLE education_i18n DROP CONSTRAINT FK_15CFA527E559DFD1');
        $this->addSql('ALTER TABLE education_i18n DROP CONSTRAINT FK_15CFA5272CA1BD71');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C103979B1AD6');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C1035AEA4428');
        $this->addSql('ALTER TABLE experience_skill DROP CONSTRAINT FK_3D6F986146E90E27');
        $this->addSql('ALTER TABLE experience_skill DROP CONSTRAINT FK_3D6F98615585C142');
        $this->addSql('ALTER TABLE experience_technology DROP CONSTRAINT FK_1BC2EDF146E90E27');
        $this->addSql('ALTER TABLE experience_technology DROP CONSTRAINT FK_1BC2EDF14235D463');
        $this->addSql('ALTER TABLE experience_i18n DROP CONSTRAINT FK_AB46D78BE559DFD1');
        $this->addSql('ALTER TABLE experience_i18n DROP CONSTRAINT FK_AB46D78B46E90E27');
        $this->addSql('ALTER TABLE language DROP CONSTRAINT FK_D4DB71B55AEA4428');
        $this->addSql('ALTER TABLE language_i18n DROP CONSTRAINT FK_CD5FF2DAE559DFD1');
        $this->addSql('ALTER TABLE language_i18n DROP CONSTRAINT FK_CD5FF2DA82F1BAF4');
        $this->addSql('ALTER TABLE link DROP CONSTRAINT FK_36AC99F1166D1F9C');
        $this->addSql('ALTER TABLE link DROP CONSTRAINT FK_36AC99F15AEA4428');
        $this->addSql('ALTER TABLE link_i18n DROP CONSTRAINT FK_4E118A3FE559DFD1');
        $this->addSql('ALTER TABLE link_i18n DROP CONSTRAINT FK_4E118A3FADA40271');
        $this->addSql('ALTER TABLE link_i18n DROP CONSTRAINT FK_4E118A3F166D1F9C');
        $this->addSql('ALTER TABLE picture DROP CONSTRAINT FK_16DB4F89166D1F9C');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE6BF700BD');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE979B1AD6');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEC32A47EE');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EE5AEA4428');
        $this->addSql('ALTER TABLE project_technology DROP CONSTRAINT FK_ECC5297F166D1F9C');
        $this->addSql('ALTER TABLE project_technology DROP CONSTRAINT FK_ECC5297F4235D463');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60166D1F9C');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60BAD26311');
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE9166D1F9C');
        $this->addSql('ALTER TABLE project_skill DROP CONSTRAINT FK_4D68EDE95585C142');
        $this->addSql('ALTER TABLE project_i18n DROP CONSTRAINT FK_C6C7D08EE559DFD1');
        $this->addSql('ALTER TABLE project_i18n DROP CONSTRAINT FK_C6C7D08E166D1F9C');
        $this->addSql('ALTER TABLE school DROP CONSTRAINT FK_F99EDABBF92F3E70');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE4775AEA4428');
        $this->addSql('ALTER TABLE skill_i18n DROP CONSTRAINT FK_B8178424E559DFD1');
        $this->addSql('ALTER TABLE skill_i18n DROP CONSTRAINT FK_B81784245585C142');
        $this->addSql('ALTER TABLE status_i18n DROP CONSTRAINT FK_C750B502E559DFD1');
        $this->addSql('ALTER TABLE status_i18n DROP CONSTRAINT FK_C750B5026BF700BD');
        $this->addSql('ALTER TABLE tag_i18n DROP CONSTRAINT FK_1159A720E559DFD1');
        $this->addSql('ALTER TABLE tag_i18n DROP CONSTRAINT FK_1159A720BAD26311');
        $this->addSql('ALTER TABLE technology DROP CONSTRAINT FK_F463524D5AEA4428');
        $this->addSql('ALTER TABLE work_type DROP CONSTRAINT FK_751DE6115AEA4428');
        $this->addSql('ALTER TABLE work_type_i18n DROP CONSTRAINT FK_4A5175CBE559DFD1');
        $this->addSql('ALTER TABLE work_type_i18n DROP CONSTRAINT FK_4A5175CB108734B1');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE country_i18n');
        $this->addSql('DROP TABLE curriculum');
        $this->addSql('DROP TABLE curriculum_i18n');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE education_skill');
        $this->addSql('DROP TABLE education_technology');
        $this->addSql('DROP TABLE education_i18n');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE experience_skill');
        $this->addSql('DROP TABLE experience_technology');
        $this->addSql('DROP TABLE experience_i18n');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE language_i18n');
        $this->addSql('DROP TABLE link');
        $this->addSql('DROP TABLE link_i18n');
        $this->addSql('DROP TABLE locale');
        $this->addSql('DROP TABLE picture');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_technology');
        $this->addSql('DROP TABLE project_tag');
        $this->addSql('DROP TABLE project_skill');
        $this->addSql('DROP TABLE project_i18n');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_i18n');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE status_i18n');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE tag_i18n');
        $this->addSql('DROP TABLE technology');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE work_type');
        $this->addSql('DROP TABLE work_type_i18n');
    }
}
